### ISSUE TITLE
Init todo

### ISSUE THREAD

**Issue by Zeko369** [Zeko369/cra-template-zeko369#2]
- [ ] Add `@types` folder
- [ ] Add testing (with examples)
- [ ] Add script to setup
	- [ ] Cypress
- [ ] Setup build script (custom prebuild scripts)

- [ ] Gatsby/Next?
